POST http://localhost:8080/admin/saveItem
Content-Type: application/json
X-Token: 80b0f0d6-16bf-4f8a-b657-69cc40b9b574

{
  "name": "Drill",
  "description": "Drill description",
  "tags": [
    {
      "id": 1,
      "tag": "tools"
    }
  ]
}

###

PATCH http://localhost:8080/admin/updateItem
Content-Type: application/json
X-Token: 455db1a0-54f8-49df-bcfc-bae97225140d

{
  "name": "Shovel",
  "description": "Some other description",
  "tags": [
    {
      "id": 1,
      "tag": "tools"
    },
    {
      "id": 2,
      "tag": "gardening"
    },
    {
      "id": 3,
      "tag": "for home"
    }
  ]
}

###
PATCH http://localhost:8080/admin/forceUpdate
Content-Type: application/json
X-Token: 455db1a0-54f8-49df-bcfc-bae97225140d

{
  "name": "Shovel",
  "description": "Some other description",
  "tags": [
    {
      "id": 1,
      "tag": "tools"
    },
    {
      "id": 2,
      "tag": "gardening"
    },
    {
      "id": 3,
      "tag": "for home"
    }
  ]
}

###

POST http://localhost:8080/users/addToCart
Content-Type: application/json
X-Token: 455db1a0-54f8-49df-bcfc-bae97225140d

{
  "name": "Shovel",
  "description": "Some other description",
  "tags": [
    {
      "id": 1,
      "tag": "tools"
    },
    {
      "id": 2,
      "tag": "gardening"
    },
    {
      "id": 3,
      "tag": "for home"
    }
  ]
}

###

POST http://localhost:8080/users/removeFromCart
Content-Type: application/json
X-Token: 455db1a0-54f8-49df-bcfc-bae97225140d

{
  "name": "Shovel",
  "description": "Some other description",
  "tags": [
    {
      "id": 1,
      "tag": "tools"
    },
    {
      "id": 2,
      "tag": "gardening"
    },
    {
      "id": 3,
      "tag": "for home"
    }
  ]
}

###

POST http://localhost:8080/users/buy
Content-Type: application/json
X-Token: f9442323-56fa-49d4-924f-5384a15151e4

{
  "id": 1,
  "user": {
    "type": "USER",
    "nickname": "noximt",
    "password": "qwerty",
    "email": "noximt@gmail.com"
  },
  "items": [
    {
      "name": "Shovel",
      "description": "Some other description",
      "tags": [
        {
          "id": 1,
          "tag": "tools"
        },
        {
          "id": 2,
          "tag": "gardening"
        },
        {
          "id": 3,
          "tag": "for home"
        }
      ]
    }
  ]
}

###

POST http://localhost:8080/users/searchByTags
Content-Type: application/json
X-Token: 80b0f0d6-16bf-4f8a-b657-69cc40b9b574

[
  {
    "id": 1,
    "tag": "tools"
  },
  {
    "id": 2,
    "tag": "gardening"
  },
  {
    "id": 3,
    "tag": "for home"
  }
]


###

GET http://localhost:8080/users/searchByDescription?description=Drill description
X-Token: 80b0f0d6-16bf-4f8a-b657-69cc40b9b574

###