POST http://localhost:8080/users/reg
Content-Type: application/json

{
  "type": "ADMIN",
  "nickname": "admin1",
  "password": "qwertyadmin",
  "email": "notneeded@email.com"
}

###

POST http://localhost:8080/users/reg
Content-Type: application/json

{
  "type": "USER",
  "nickname": "user1",
  "password": "simplePassword",
  "email": "some@gmail.com"
}

###

POST http://localhost:8080/users/reg
Content-Type: application/json

{
  "type": "USER",
  "nickname": "user2",
  "password": "difficultPass",
  "email": "email@gmail.com"
}

###

GET http://localhost:8080/users/auth?nickname=admin1&password=qwertyadmin

###

GET http://localhost:8080/users/auth?nickname=user1&password=simplePassword

###

GET http://localhost:8080/users/auth?nickname=user2&password=difficultPass

###