POST http://localhost:8080/users/reg
Content-Type: application/json

{
  "type": "USER",
  "nickname": "noximt",
  "password": "test",
  "email": "noximt@gmail.com"
}

###

GET http://localhost:8080/users/auth?nickname=noximt&password=test

###

POST http://localhost:8080/admin/saveItem
Content-Type: application/json
X-Token:e417ed34-04c5-4b9c-81af-a4b0df587bc9

{
  "name": "Drill",
  "description": "Some description",
  "tags": [
    {"id": 1,
      "tag": "tools"},
    {"id": 2,
      "tag": "electronics"}
  ]
}

###

PATCH http://localhost:8080/admin/updateItem
Content-Type: application/json
X-Token: 0199d7cc-5b97-4b4d-8b1c-2bb11916413b

{
  "name": "Drill",
  "description": "Some more description",
  "tags": [
    {"id": 1,
      "tag": "tools"}
  ]
}

###
PATCH http://localhost:8080/admin/forceUpdate
Content-Type: application/json
X-Token: 0199d7cc-5b97-4b4d-8b1c-2bb11916413b

{
  "name": "Drill",
  "description": "Some more description",
  "tags": [
    {"id": 1,
    "tag": "tools"}
  ]
}

###

POST http://localhost:8080/users/addToCart
Content-Type: application/json
X-Token: e417ed34-04c5-4b9c-81af-a4b0df587bc9

{
  "name": "Drill"
}

###

POST http://localhost:8080/users/removeFromCart
Content-Type: application/json
X-Token: 0e24779a-c277-48cc-b5f5-7ce2cefeadf5

{
  "name": "Drill"
}

###

POST http://localhost:8080/users/buy
Content-Type: application/json
X-Token: f9442323-56fa-49d4-924f-5384a15151e4

{
  "id": 1,
  "user": {
    "type": "USER",
    "nickname": "noximt",
    "password": "qwerty",
    "email": "noximt@gmail.com"
  },
  "items": [
    {
      "name": "Drill",
      "description": "Some description"
    }
  ]
}
